<?php

namespace CHRIST\Common\Repository;

/**
 * RocEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RocEtablissementRepository extends Master\AbstractRocEtablissementRepository
{
    
}
