<?php

namespace CHRIST\Common\Repository;

/**
 * RocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RocRepository extends Master\AbstractRocRepository
{
    
}
