<?php

namespace CHRIST\Common\Repository;

/**
 * SambaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SambaRepository extends Master\AbstractSambaRepository
{
    
}
