#
# INCLUDE
################################################################################
imports:
    - { resource: doctrine.yml }
    - { resource: parameters.yml }
################################################################################

#
# CONFIGURATION
################################################################################
Livre:
    ftp:
        configuration:
            host: TheWebHoster
            port: 2021
            login: NotKnown
            password: NotKnown
################################################################################
