parameters:
    application:
        name: Christian ALCON
        version: 
            numero: '0.3.0'
            date:   mars 2016
    module: Portail
    path:
        root: <?php dirname(dirname(__DIR__)); ?>/
        rootCommon: <?php dirname(dirname(__DIR__)); ?>/app/
        rootModules: <?php dirname(dirname(__DIR__)); ?>/src/
        cache: <?php dirname(dirname(__DIR__)); ?>/cache/
    prod: 
        db:
            driverClass: ~
            host: localhost
            port: ~
            user: root
            password: 
    local: 
        db:
            driverClass: ~
            host: localhost
            port: ~
            user: root
            password: 
