<?php

namespace CHRIST\Common\Repository\Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use Doctrine\ORM\EntityRepository;

/**
 * ILoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    function getAvailableUser(\CHRIST\Common\Entity\Login\Role $role)
    {
        $qb = $this->getEntityManager()
            ->getRepository('\CHRIST\Common\Entity\Login\User')
            ->createQueryBuilder('u');
    
        if (!$role->getUsers()->isEmpty()) {
            $qb->where($qb->expr()->notIn('u.login', $role->getUsersUsed()));
        }
            
        return $qb->orderBy('u.login', 'ASC')
                    ->getQuery()
                    ->getResult();
    }
}
